package com.finclear.api;

import com.finclear.domain.*; import com.finclear.repository.*; import org.springframework.web.bind.annotation.*; import java.math.*; import java.time.*; import java.util.*;

@RestController @RequestMapping("/api/v1/control") public class ControlCenterController {
 private final PaymentRepository payments; private final AccountRepository accounts; private final ExceptionCaseRepository exceptions;
 public ControlCenterController(PaymentRepository payments,AccountRepository accounts,ExceptionCaseRepository exceptions){this.payments=payments;this.accounts=accounts;this.exceptions=exceptions;}
 @GetMapping("/overview") public Map<String,Object> overview(){var ps=payments.findTop50ByOrderByCreatedAtDesc();var balance=accounts.findAll().stream().map(Account::getAvailableBalance).reduce(BigDecimal.ZERO,BigDecimal::add);var volume=ps.stream().map(Payment::getAmount).reduce(BigDecimal.ZERO,BigDecimal::add);var open=exceptions.findAllByOrderByCreatedAtDesc().stream().filter(x->!"RESOLVED".equals(x.getStatus())).toList();var exposure=open.stream().map(ExceptionCase::getAmount).reduce(BigDecimal.ZERO,BigDecimal::add);return Map.of("availableBalance",balance,"processedVolume",volume,"paymentCount",ps.size(),"openExceptions",open.size(),"exposure",exposure,"settlementHealth",open.isEmpty()?"HEALTHY":"ATTENTION","updatedAt",Instant.now());}
 @GetMapping("/exceptions") public List<Map<String,Object>> cases(){return exceptions.findAllByOrderByCreatedAtDesc().stream().map(x->Map.<String,Object>of("id",x.getId(),"title",x.getTitle(),"category",x.getCategory(),"severity",x.getSeverity(),"amount",x.getAmount(),"currency",x.getCurrency(),"status",x.getStatus(),"owner",x.getOwner(),"evidence",x.getEvidence(),"createdAt",x.getCreatedAt())).toList();}
 @PostMapping("/exceptions/{id}/resolve") public Map<String,Object> resolve(@PathVariable UUID id){var x=exceptions.findById(id).orElseThrow(()->new IllegalArgumentException("Exception not found"));x.setStatus("RESOLVED");x.setUpdatedAt(Instant.now());exceptions.save(x);return Map.of("id",x.getId(),"status",x.getStatus());}
 @GetMapping("/explain") public Map<String,Object> explain(){var open=exceptions.findAllByOrderByCreatedAtDesc().stream().filter(x->!"RESOLVED".equals(x.getStatus())).toList();var exposure=open.stream().map(ExceptionCase::getAmount).reduce(BigDecimal.ZERO,BigDecimal::add);return Map.of("headline",open.isEmpty()?"All money movements are reconciled.":"Money needs attention before the next settlement window.","summary",open.isEmpty()?"No open reconciliation exceptions are currently recorded.":open.size()+" exceptions account for "+exposure.setScale(2)+" INR of operational exposure.","nextAction",open.isEmpty()?"Monitor the next settlement file.":"Resolve the highest-severity exception and document the decision trail.","confidence",open.isEmpty()?"HIGH":"MEDIUM");}
}
